import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/shared/footer";
import localFont from "next/font/local";
import QueryClientProviderWrapper from "@/components/query-wrapper";

const HelveticaNeue = localFont({
  src: "../app/fonts/HelveticaNeueThin.otf",
  variable: "--font-neue",
});

export const metadata: Metadata = {
  title: "Cints Estate | Premium Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${HelveticaNeue.variable} antialiased overflow-x-hidden`}
      >
        <QueryClientProviderWrapper>
          {children}
          <Footer />
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
