import type { Metadata } from "next";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import Footer from "@/components/shared/footer";
import localFont from "next/font/local";
import QueryClientProviderWrapper from "@/components/query-wrapper";
import { Toaster } from "@/components/ui/sonner";

const HelveticaNeue = localFont({
  src: "../app/fonts/HelveticaNeueThin.otf",
  variable: "--font-neue",
});

export const metadata: Metadata = {
  title: "Cints Estate | Premium Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${HelveticaNeue.variable} antialiased overflow-x-hidden`}
      >
        <QueryClientProviderWrapper>
          <div className="w-full mx-auto [@media(min-width:1920px)]:max-w-[1440px]">
            {children}
            <Toaster />
            <Footer />
          </div>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
